/*
 * TestSwing.java
 *
 * Created on __DATE__, __TIME__
 */

package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import com.sun.org.apache.xalan.internal.xsltc.compiler.Template;

import core.BaseEntity;
import core.Patch;
import core.SimulatorAttribute;
import core.TermiteSimulator;

/**
 *
 * @author  __USER__
 */
public class GraphDisplay extends javax.swing.JFrame {

	/** Creates new form TestSwing */
	public GraphDisplay() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		resultJPanel = new javax.swing.JPanel();
		SimulatorResultJLabel = new javax.swing.JLabel();
		graphJPanel = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		settingJpane = new javax.swing.JPanel();
		paramJPanel = new javax.swing.JPanel();
		widthJLabel = new javax.swing.JLabel();
		widthJTextField = new javax.swing.JTextField();
		heightJLabel = new javax.swing.JLabel();
		heightJTextField = new javax.swing.JTextField();
		soldierTermiteNumberJLabel = new javax.swing.JLabel();
		soldierTermiteNumberJTextField = new javax.swing.JTextField();
		workerTermiteNumberJLabel = new javax.swing.JLabel();
		workerTermiteNumberJTextField = new javax.swing.JTextField();
		chipNumberJLabel = new javax.swing.JLabel();
		chipNumberJTextField = new javax.swing.JTextField();
		loopNumberJLabel = new javax.swing.JLabel();
		loopNumberJTextField = new javax.swing.JTextField();
		timeSpanJLabel = new javax.swing.JLabel();
		timeSpanJTextField = new javax.swing.JTextField();
		ensureJButton = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		representJTextArea = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		SimulatorSettingJLabel = new javax.swing.JLabel();
		simulatorJMenuBar = new javax.swing.JMenuBar();
		fileJMenu = new javax.swing.JMenu();
		exitJMenuItem = new javax.swing.JMenuItem();
		helpJMenu = new javax.swing.JMenu();
		aboutJMenuItem = new javax.swing.JMenuItem();
		simulatorJMenuBar1 = new javax.swing.JMenuBar();
		fileJMenu1 = new javax.swing.JMenu();
		exitJMenuItem1 = new javax.swing.JMenuItem();
		helpJMenu1 = new javax.swing.JMenu();
		aboutJMenuItem1 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("SimulatorTermite--ZY1114213--\u8bb8\u56fd\u519b");
		setName("SimulatorTermite");

		resultJPanel.setBackground(new java.awt.Color(204, 204, 255));

		SimulatorResultJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 14));
		SimulatorResultJLabel.setText("Simulator Graph Result");

		graphJPanel.setBackground(new java.awt.Color(153, 153, 255));

		javax.swing.GroupLayout graphJPanelLayout = new javax.swing.GroupLayout(
				graphJPanel);
		graphJPanel.setLayout(graphJPanelLayout);
		graphJPanelLayout.setHorizontalGroup(graphJPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 554, Short.MAX_VALUE));
		graphJPanelLayout.setVerticalGroup(graphJPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 559, Short.MAX_VALUE));

		javax.swing.GroupLayout resultJPanelLayout = new javax.swing.GroupLayout(
				resultJPanel);
		resultJPanel.setLayout(resultJPanelLayout);
		resultJPanelLayout
				.setHorizontalGroup(resultJPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								resultJPanelLayout
										.createSequentialGroup()
										.addGroup(
												resultJPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																resultJPanelLayout
																		.createSequentialGroup()
																		.addGap(
																				206,
																				206,
																				206)
																		.addComponent(
																				SimulatorResultJLabel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				174,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																resultJPanelLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				graphJPanel,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		resultJPanelLayout
				.setVerticalGroup(resultJPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								resultJPanelLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(SimulatorResultJLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												graphJPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(124, 124, 124)));

		jPanel1.setBackground(new java.awt.Color(204, 255, 204));

		settingJpane.setBackground(new java.awt.Color(204, 255, 204));

		widthJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 12));
		widthJLabel.setText("width:");
		widthJLabel.setToolTipText("\u6a2a\u5411\u683c\u5b50\u6570");

		widthJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		widthJTextField.setText("20");
		widthJTextField.setAutoscrolls(false);
		widthJTextField.setPreferredSize(new java.awt.Dimension(50, 23));

		heightJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 12));
		heightJLabel.setText("height:");
		heightJLabel.setToolTipText("\u7eb5\u5411\u683c\u5b50\u6570");

		heightJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		heightJTextField.setText("20");
		heightJTextField.setMinimumSize(new java.awt.Dimension(50, 23));
		heightJTextField.setPreferredSize(new java.awt.Dimension(50, 23));

		soldierTermiteNumberJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 12));
		soldierTermiteNumberJLabel.setText("soldier:");
		soldierTermiteNumberJLabel.setToolTipText("\u5175\u8681\u4e2a\u6570");

		soldierTermiteNumberJTextField
				.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		soldierTermiteNumberJTextField.setText("40");
		soldierTermiteNumberJTextField.setPreferredSize(new java.awt.Dimension(
				50, 23));

		workerTermiteNumberJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 12));
		workerTermiteNumberJLabel.setText("worker:");
		workerTermiteNumberJLabel.setToolTipText("\u5de5\u8681\u4e2a\u6570");

		workerTermiteNumberJTextField
				.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		workerTermiteNumberJTextField.setText("40");
		workerTermiteNumberJTextField.setPreferredSize(new java.awt.Dimension(
				50, 23));

		chipNumberJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 12));
		chipNumberJLabel.setText("chip:");
		chipNumberJLabel.setToolTipText("\u6728\u7247\u5757\u6570");

		chipNumberJTextField
				.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		chipNumberJTextField.setText("80");
		chipNumberJTextField.setPreferredSize(new java.awt.Dimension(50, 23));

		loopNumberJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 12));
		loopNumberJLabel.setText("loopNum:");
		loopNumberJLabel.setToolTipText("\u5faa\u73af\u6b21\u6570");

		loopNumberJTextField
				.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		loopNumberJTextField.setText("100");
		loopNumberJTextField.setPreferredSize(new java.awt.Dimension(50, 23));

		timeSpanJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 12));
		timeSpanJLabel.setText("timeSpan:");
		timeSpanJLabel
				.setToolTipText("\u6bcf\u6b21\u5faa\u73af\u7684\u65f6\u95f4\u95f4\u9694");

		timeSpanJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
		timeSpanJTextField.setText("500");
		timeSpanJTextField.setPreferredSize(new java.awt.Dimension(50, 23));

		javax.swing.GroupLayout paramJPanelLayout = new javax.swing.GroupLayout(
				paramJPanel);
		paramJPanel.setLayout(paramJPanelLayout);
		paramJPanelLayout
				.setHorizontalGroup(paramJPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								paramJPanelLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												paramJPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																widthJLabel)
														.addComponent(
																soldierTermiteNumberJLabel)
														.addComponent(
																soldierTermiteNumberJTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																heightJLabel)
														.addComponent(
																workerTermiteNumberJLabel)
														.addComponent(
																workerTermiteNumberJTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																chipNumberJLabel)
														.addComponent(
																chipNumberJTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																loopNumberJLabel)
														.addComponent(
																loopNumberJTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																timeSpanJTextField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																timeSpanJLabel)
														.addGroup(
																paramJPanelLayout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				widthJTextField,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				heightJTextField,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addGap(5, 5, 5)));
		paramJPanelLayout
				.setVerticalGroup(paramJPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								paramJPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(widthJLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												widthJTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(heightJLabel)
										.addGap(14, 14, 14)
										.addComponent(
												heightJTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												soldierTermiteNumberJLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												soldierTermiteNumberJTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(workerTermiteNumberJLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												workerTermiteNumberJTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(chipNumberJLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												chipNumberJTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(loopNumberJLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												loopNumberJTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												timeSpanJLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												28,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												timeSpanJTextField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		ensureJButton.setText("OK");
		ensureJButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				GetUserSettingParam(evt);
			}
		});

		javax.swing.GroupLayout settingJpaneLayout = new javax.swing.GroupLayout(
				settingJpane);
		settingJpane.setLayout(settingJpaneLayout);
		settingJpaneLayout
				.setHorizontalGroup(settingJpaneLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								settingJpaneLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												settingJpaneLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																settingJpaneLayout
																		.createSequentialGroup()
																		.addComponent(
																				paramJPanel,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addContainerGap())
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																settingJpaneLayout
																		.createSequentialGroup()
																		.addComponent(
																				ensureJButton)
																		.addGap(
																				26,
																				26,
																				26)))));
		settingJpaneLayout
				.setVerticalGroup(settingJpaneLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								settingJpaneLayout
										.createSequentialGroup()
										.addGap(43, 43, 43)
										.addComponent(
												paramJPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(ensureJButton)
										.addContainerGap(43, Short.MAX_VALUE)));

		representJTextArea.setBackground(new java.awt.Color(204, 204, 255));
		representJTextArea.setColumns(20);
		representJTextArea.setEditable(false);
		representJTextArea.setRows(5);
		jScrollPane1.setViewportView(representJTextArea);

		jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 14));
		jLabel1.setText("Simulator Text Result (chip:soldier:worker/withChip)");

		SimulatorSettingJLabel.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 2, 14));
		SimulatorSettingJLabel.setText("Simulator  Setting");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				366,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				SimulatorSettingJLabel))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				443,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				settingJpane,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(15, 15, 15)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																SimulatorSettingJLabel)
														.addComponent(jLabel1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																settingJpane,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																554,
																Short.MAX_VALUE))
										.addContainerGap()));

		fileJMenu.setText("File");

		exitJMenuItem.setText("Exit");
		exitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitJMenuItemActionPerformed(evt);
			}
		});
		fileJMenu.add(exitJMenuItem);

		simulatorJMenuBar.add(fileJMenu);

		helpJMenu.setText("Help");

		aboutJMenuItem.setText("About");
		helpJMenu.add(aboutJMenuItem);

		simulatorJMenuBar.add(helpJMenu);

		fileJMenu1.setText("File");

		exitJMenuItem1.setText("Exit");
		exitJMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitJMenuItemActionPerformed(evt);
			}
		});
		fileJMenu1.add(exitJMenuItem1);

		simulatorJMenuBar1.add(fileJMenu1);

		helpJMenu1.setText("Help");

		aboutJMenuItem1.setText("About");
		helpJMenu1.add(aboutJMenuItem1);

		simulatorJMenuBar1.add(helpJMenu1);

		setJMenuBar(simulatorJMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												resultJPanel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								false).addComponent(resultJPanel,
								javax.swing.GroupLayout.Alignment.LEADING, 0,
								610, Short.MAX_VALUE).addComponent(jPanel1,
								javax.swing.GroupLayout.Alignment.LEADING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)).addGap(21, 21, 21)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void exitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private int width;
	private int height;
	private int section_width;
	private int section_height;
	private int remainder_width;
	private int remainder_height;
	private Graphics displayGraphics;
	private int timespan = 10;

	private void ClearPatch(){
		Patch[][] temp = termiteSimulator.world.getPitchs();
		for(int i=0;i<simulatorAttribute.getWidth();i++){
			for(int j=0;j<simulatorAttribute.getHeigth();j++){
				System.out.println(i);
				if(temp[i][j].getChipNumber()>0 
						|| temp[i][j].getSoldierTermiteNumber()>0
						|| temp[i][j].getWorkerTermiteNumber()>0){
					displayGraphics.clearRect(
							remainder_width+i*section_width,
							remainder_height+i*section_height,
							remainder_width+i*section_width,
							remainder_height+i*section_height);
					/*displayGraphics.drawLine(
							remainder_width+i*section_width,
							remainder_height+i*section_height,
							remainder_width+i*section_width,
							remainder_height+(i+1)*section_height);
					displayGraphics.drawLine(
							remainder_width+i*section_width,
							remainder_height+i*section_height,
							remainder_width+(i+1)*section_width,
							remainder_height+i*section_height);
					displayGraphics.drawLine(
							remainder_width+(i+1)*section_width,
							remainder_height+i*section_height,
							remainder_width+(i+1)*section_width,
							remainder_height+(i+1)*section_height);
					displayGraphics.drawLine(
							remainder_width+i*section_width,
							remainder_height+(i+1)*section_height,
							remainder_width+(i+1)*section_width,
							remainder_height+(i+1)*section_height);
					*/
				}
					
			}
		}
	}
	
	private void DrawGrid(JPanel panel, SimulatorAttribute simulatorAttribute) {
		width = panel.getWidth();
		height = panel.getHeight();

		section_width = width / simulatorAttribute.getWidth();
		section_height = height / simulatorAttribute.getHeigth();

		remainder_width = width - section_width * simulatorAttribute.getWidth();
		remainder_height = height - section_height
				* simulatorAttribute.getHeigth();

		displayGraphics.clearRect(0, 0, width, height);

		for (int i = 0; i <= simulatorAttribute.getWidth(); i++) {
			displayGraphics.drawLine(remainder_width / 2 + section_width * i,
					remainder_height / 2, remainder_width / 2 + section_width
							* i, height - remainder_height / 2);
		}

		for (int i = 0; i <= simulatorAttribute.getHeigth(); i++) {
			displayGraphics.drawLine(remainder_width / 2, remainder_height / 2
					+ section_height * i, width - remainder_width / 2,
					remainder_height / 2 + section_height * i);
		}
	}

	private void GetUserSettingParam(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		simulatorAttribute
				.setWidth(Integer.parseInt(widthJTextField.getText()));
		simulatorAttribute.setHeigth(Integer.parseInt(heightJTextField
				.getText()));
		simulatorAttribute.setSoliderTermiteNumber(Integer
				.parseInt(soldierTermiteNumberJTextField.getText()));
		simulatorAttribute.setWorkerTermiteNumber(Integer
				.parseInt(workerTermiteNumberJTextField.getText()));
		simulatorAttribute.setChipNumber(Integer.parseInt(chipNumberJTextField
				.getText()));
		simulatorAttribute.setLoopNumber(Integer.parseInt(loopNumberJTextField
				.getText()));
		timespan = Integer.parseInt(timeSpanJTextField.getText());

		//simulatorAttribute.PrintAttributes();
		termiteSimulator = new TermiteSimulator(
				simulatorAttribute);
		//termiteSimulator.StartTermiteSimulator();
		termiteSimulator.IntialSimulator();

		displayGraphics = graphJPanel.getGraphics();
		DrawGrid(graphJPanel, simulatorAttribute);

		representJTextArea.setEditable(false);
		representJTextArea.setText("");

		//DrawGrid(graphJPanel, simulatorAttribute);
		for (int i = 0; i < simulatorAttribute.getLoopNumber(); i++) {
			for (BaseEntity baseEntity : termiteSimulator.world.getEntities()) {
				baseEntity.DoAction();
			}
			try {
				Thread.sleep(timespan);
			} catch (Exception e) {
				// TODO: handle exception
			}

			//ClearPatch();
			displayGraphics.clearRect(0, 0, width, height);
			DrawGrid(graphJPanel, simulatorAttribute);
			termiteSimulator.world.PrintWorldGraphic(displayGraphics,
					remainder_width / 2, remainder_height / 2, section_width,
					section_height);
			
			if (simulatorAttribute.getLoopNumber() > 50
					&& i > simulatorAttribute.getLoopNumber() - 50) {
				termiteSimulator.world.PrintWorldRichGraph(representJTextArea);
			} else if (simulatorAttribute.getLoopNumber() < 50) {
				termiteSimulator.world.PrintWorldRichGraph(representJTextArea);
			}
			
			//if the result reach stable state before the number of loop,stop 
			//the loop and only print the final result in text ,else print the
			//last 50 results
			//¹¤ÒÏÊýÄ¿Ð¡ÓÚÄ¾Æ¬ÊýÄ¿_stable state 1
			if(simulatorAttribute.getChipNumber() > simulatorAttribute.getWorkerTermiteNumber()){
				if(termiteSimulator.world.isOnlyOnePatchOwnChip()){
					representJTextArea.setText("");
					termiteSimulator.world.PrintWorldRichGraph(representJTextArea);
					representJTextArea.append("\n the total run times is :" + String.valueOf(i));
					i = simulatorAttribute.getLoopNumber();
				}
			}
			//¹¤ÒÏÊýÄ¿´óÓÚÄ¾Æ¬ÊýÄ¿_stable state 2
			else if(simulatorAttribute.getChipNumber() < simulatorAttribute.getWorkerTermiteNumber()){
				if(termiteSimulator.world.isNoPatchOwnChip()){
					representJTextArea.setText("");
					termiteSimulator.world.PrintWorldRichGraph(representJTextArea);
					representJTextArea.append("\n the total run times is :" + String.valueOf(i));
					i = simulatorAttribute.getLoopNumber();
				}	
			}
			//termiteSimulator.world.PrintWorldBriefGraph(representJTextArea);
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GraphDisplay().setVisible(true);
			}
		});
	}

	public void RunGui() {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GraphDisplay().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel SimulatorResultJLabel;
	private javax.swing.JLabel SimulatorSettingJLabel;
	private javax.swing.JMenuItem aboutJMenuItem;
	private javax.swing.JMenuItem aboutJMenuItem1;
	private javax.swing.JLabel chipNumberJLabel;
	private javax.swing.JTextField chipNumberJTextField;
	private javax.swing.JButton ensureJButton;
	private javax.swing.JMenuItem exitJMenuItem;
	private javax.swing.JMenuItem exitJMenuItem1;
	private javax.swing.JMenu fileJMenu;
	private javax.swing.JMenu fileJMenu1;
	private javax.swing.JPanel graphJPanel;
	private javax.swing.JLabel heightJLabel;
	private javax.swing.JTextField heightJTextField;
	private javax.swing.JMenu helpJMenu;
	private javax.swing.JMenu helpJMenu1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel loopNumberJLabel;
	private javax.swing.JTextField loopNumberJTextField;
	private javax.swing.JPanel paramJPanel;
	private javax.swing.JTextArea representJTextArea;
	private javax.swing.JPanel resultJPanel;
	private javax.swing.JPanel settingJpane;
	private javax.swing.JMenuBar simulatorJMenuBar;
	private javax.swing.JMenuBar simulatorJMenuBar1;
	private javax.swing.JLabel soldierTermiteNumberJLabel;
	private javax.swing.JTextField soldierTermiteNumberJTextField;
	private javax.swing.JLabel timeSpanJLabel;
	private javax.swing.JTextField timeSpanJTextField;
	private javax.swing.JLabel widthJLabel;
	private javax.swing.JTextField widthJTextField;
	private javax.swing.JLabel workerTermiteNumberJLabel;
	private javax.swing.JTextField workerTermiteNumberJTextField;
	// End of variables declaration//GEN-END:variables

	private core.SimulatorAttribute simulatorAttribute = new core.SimulatorAttribute();
	private core.TermiteSimulator termiteSimulator ;

}